### ISSUE TITLE
UI: 移动端优化

### ISSUE THREAD

**Issue by yjl9903** [yjl9903/resonance-market#13]

**Comment by Velsun3366** [comment]
要用媒体查询？

**Comment by yjl9903** [comment]
> 要用媒体查询？

结构完全变了，没法用媒体查询

用 vueuse 里的 breakpoints 相关，拿到当前屏幕的宽度，重新渲染一份吧

**Comment by Velsun3366** [comment]
要整移动端了，可以脑补出一些兼容问题了，特别是IOS，汗流浃背了要，我好菜

**Comment by Ximu-Luya** [comment]
大佬，我正在基于移动端写一套PC/移动端自适应的响应式页面，也有部分计划的其他计算功能。目前我已经基于你现在线上页面的接口做好了数据处理，问题是我这整套页面结构可能和你现有的页面不太相同，请问这部分你有什么计划吗？我可以向你这个仓库提PR合并吗？还是不接受这种差异过大的页面更改？我是服务端苦手，所以暂时只做了前端

**Comment by Ximu-Luya** [comment]
> 大佬，我正在基于移动端写一套PC/移动端自适应的响应式页面，也有部分计划的其他计算功能。目前我已经基于你现在线上页面的接口做好了数据处理，问题是我这整套页面结构可能和你现有的页面不太相同，请问这部分你有什么计划吗？我可以向你这个仓库提PR合并吗？还是不接受这种差异过大的页面更改？我是服务端苦手，所以暂时只做了前端

![image](https://github.com/yjl9903/resonance-market/assets/53012237/2a5c64cf-1313-4fc6-9133-8ebbb2519b06)
货物列表效果大致如上，整体UI与功能参考蚂蚁财富的基金、股票页面。

**Comment by yjl9903** [comment]
@Ximu-Luya 看起来数据呈现逻辑完全不同，有在线的demo可以看看吗？

如果PR涉及了大规模页面结构变更的话，可能就不接受了，因为我这里还需要先重构目前的混乱逻辑。

另一种可能是，你可以发 PR 单独添加你的相关页面，作为实验性的UI，后续再进行整合。

**Comment by yjl9903** [comment]
> > 大佬，我正在基于移动端写一套PC/移动端自适应的响应式页面，也有部分计划的其他计算功能。目前我已经基于你现在线上页面的接口做好了数据处理，问题是我这整套页面结构可能和你现有的页面不太相同，请问这部分你有什么计划吗？我可以向你这个仓库提PR合并吗？还是不接受这种差异过大的页面更改？我是服务端苦手，所以暂时只做了前端
> 
> ![image](https://private-user-images.githubusercontent.com/53012237/310541643-2a5c64cf-1313-4fc6-9133-8ebbb2519b06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzcwNjUsIm5iZiI6MTcwOTczNjc2NSwicGF0aCI6Ii81MzAxMjIzNy8zMTA1NDE2NDMtMmE1YzY0Y2YtMTMxMy00ZmM2LTkxMzMtOGViYmIyNTE5YjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE0NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmE3MWJkZjE0NDQ3NmI2M2JkZDdiNWQyZWQzZjY3NjMxZmJmNjllZmQzOGJjYTc0NzM1Mzg5YjU1ZjJiNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_rb7q8gwhexuJreym_Tyd1uqfkQygbaq-k2KwWFYrI) 货物列表效果大致如上，整体UI与功能参考蚂蚁财富的基金、股票页面。

以我的感觉来看，移动端做横向滚动的体验并不好，应该采用某些其他设计。

**Comment by Ximu-Luya** [comment]
> > > 大佬，我正在基于移动端写一套PC/移动端自适应的响应式页面，也有部分计划的其他计算功能。目前我已经基于你现在线上页面的接口做好了数据处理，问题是我这整套页面结构可能和你现有的页面不太相同，请问这部分你有什么计划吗？我可以向你这个仓库提PR合并吗？还是不接受这种差异过大的页面更改？我是服务端苦手，所以暂时只做了前端
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/53012237/310541643-2a5c64cf-1313-4fc6-9133-8ebbb2519b06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzcwNjUsIm5iZiI6MTcwOTczNjc2NSwicGF0aCI6Ii81MzAxMjIzNy8zMTA1NDE2NDMtMmE1YzY0Y2YtMTMxMy00ZmM2LTkxMzMtOGViYmIyNTE5YjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE0NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmE3MWJkZjE0NDQ3NmI2M2JkZDdiNWQyZWQzZjY3NjMxZmJmNjllZmQzOGJjYTc0NzM1Mzg5YjU1ZjJiNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_rb7q8gwhexuJreym_Tyd1uqfkQygbaq-k2KwWFYrI) 货物列表效果大致如上，整体UI与功能参考蚂蚁财富的基金、股票页面。
> 
> 以我的感觉来看，移动端做横向滚动的体验并不好，应该采用某些其他设计。

这里只是货物总览，基本只会快速查看一下数据，核心还是需要点击某项货物，进入货物详情页，可以看到当前货物的所有可售地区与其报价，不过这一部分我还没有做，今晚应该可以实现一部分。
作为实验性UI这个提议我觉得挺好的，我能够接受。具体的UI设计你可以参考一下蚂蚁财富APP，或者点击zfb中的理财-基金，这个部分。

**Comment by yjl9903** [comment]
@Ximu-Luya 不用私聊，在这里留言我都会 check 的

**Comment by Ximu-Luya** [comment]
@yjl9903 那我问一个比较愚蠢的问题，我fork了项目，在本地运行时，连接数据库时报错。我已按照README中的步骤，准备好了sqlite
以下是报错信息：
```
[nuxt] [request error] [unhandled] [500] Can not find connect information
  at connect (D:\Files\Project\resonance-market\drizzle\prod\connect.ts:9:11)
```
看起来似乎是链接数据库时异常。没有TURSO_URL或TURSO_AUTH_TOKEN。
请问本地开发要怎么配置？

**Comment by Velsun3366** [comment]
> @yjl9903 那我问一个比较愚蠢的问题，我fork了项目，在本地运行时，连接数据库时报错。我已按照README中的步骤，准备好了sqlite 以下是报错信息：
> 
> ```
> [nuxt] [request error] [unhandled] [500] Can not find connect information
>   at connect (D:\Files\Project\resonance-market\drizzle\prod\connect.ts:9:11)
> ```
> 
> 看起来似乎是链接数据库时异常。没有TURSO_URL或TURSO_AUTH_TOKEN。 请问本地开发要怎么配置？

我提交的issue里可以看到

**Comment by yjl9903** [comment]
> @yjl9903 那我问一个比较愚蠢的问题，我fork了项目，在本地运行时，连接数据库时报错。我已按照README中的步骤，准备好了sqlite 以下是报错信息：
> 
> ```
> [nuxt] [request error] [unhandled] [500] Can not find connect information
>   at connect (D:\Files\Project\resonance-market\drizzle\prod\connect.ts:9:11)
> ```
> 
> 看起来似乎是链接数据库时异常。没有TURSO_URL或TURSO_AUTH_TOKEN。 请问本地开发要怎么配置？

#8

**Comment by Ximu-Luya** [comment]
我测试菜狗，因为是移动端与PC自适应，所以用TailwindCss做适配，组件逻辑使用[Naive UI](https://www.naiveui.com/zh-CN/os-theme)

**Comment by Ximu-Luya** [comment]
我之前没有着手做是因为这个数据太依赖玩家手动上传，后来在雷索纳斯手册里看到大佬留下的工具链接，深受感染遂着手开始撸代码，本来打算自己做一个不过受困于接口要准备太多，我又是服务端苦手，所以先借着大佬的数据，写一写前端的页面，既然都做好了数据处理，我就干脆来咨询大佬一起合作不了。
我尽量在两天内完成我提到的基本的功能提PR，UI上后续我会提取游戏内的素材调整得更好看一些

**Comment by Velsun3366** [comment]
> 我之前没有着手做是因为这个数据太依赖玩家手动上传，后来在雷索纳斯手册里看到大佬留下的工具链接，深受感染遂着手开始撸代码，本来打算自己做一个不过受困于接口要准备太多，我又是服务端苦手，所以先借着大佬的数据，写一写前端的页面，既然都做好了数据处理，我就干脆来咨询大佬一起合作不了。 我尽量在两天内完成我提到的基本的功能提PR，UI上后续我会提取游戏内的素材调整得更好看一些

一样是前端菜鸡

**Comment by Ximu-Luya** [comment]
在这之前我都是做的前后端分离项目，还是第一次接触nuxt，我先熟悉一下差异o(╥﹏╥)o

**Comment by Velsun3366** [comment]
> 在这之前我都是做的前后端分离项目，还是第一次接触nuxt，我先熟悉一下差异o(╥﹏╥)o

一样的感受，哈哈哈确实
